version: '3'
services:
  storage:
    image: busybox
    volumes:
      - storage:/var/lib/mysql

  mysql:
    image: mysql
    volumes:
      - storage:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
    links:
      - mysql
    ports:
      - 8070:80

volumes:
  storage: